# 스프링 메시지 색상 표시
spring:
  output.ansi.enabled : always
  profiles.include : info
  jpa:
    hibernate.ddl-auto : create
    # SQL 쿼리 확인
    properties.hibernate.format_sql : true
  # 확장성을 위해
    open-in-view : false

